Version 4
SymbolType BLOCK
RECTANGLE Normal 64 80 -64 -80
WINDOW 0 64 -80 Bottom 2
WINDOW 3 64 80 Top 2
SYMATTR Prefix X
SYMATTR Value TLV07
SYMATTR ModelFile C:\Users\Tachi\Documents\Nerd Shit\rm_electrical-supercap\SPICE_sims\libraries\TLV07.LIB
PIN -64 16 LEFT 8
PINATTR PinName IN+
PINATTR SpiceOrder 1
PIN -64 -16 LEFT 8
PINATTR PinName IN-
PINATTR SpiceOrder 2
PIN 0 -80 VRIGHT 8
PINATTR PinName VCC
PINATTR SpiceOrder 3
PIN 0 80 VLEFT 8
PINATTR PinName VEE
PINATTR SpiceOrder 4
PIN 64 0 RIGHT 8
PINATTR PinName OUT
PINATTR SpiceOrder 5
